# Generated by Django 6.0.1 on 2026-02-03 09:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_cart_options_alter_cartitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_recency', models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Weight for recency score in RFM calculation', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Recency Weight (w₁)')),
                ('weight_frequency', models.DecimalField(decimal_places=2, default=Decimal('0.35'), help_text='Weight for frequency score in RFM calculation', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Frequency Weight (w₂)')),
                ('weight_monetary', models.DecimalField(decimal_places=2, default=Decimal('0.40'), help_text='Weight for monetary score in RFM calculation', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Monetary Weight (w₃)')),
                ('base_discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum discount for any registered customer', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Base Discount Rate (%)')),
                ('max_discount_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Maximum discount achievable through RFM score', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Max Discount Rate (%)')),
                ('curve_exponent', models.DecimalField(decimal_places=2, default=Decimal('0.70'), help_text='Controls discount growth curve. <1 = fast initial growth, >1 = slow initial growth', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(3)], verbose_name='Curve Exponent (α)')),
                ('recency_max_days', models.IntegerField(default=90, help_text='Days after which recency score becomes 0', validators=[django.core.validators.MinValueValidator(7)], verbose_name='Recency Max Days')),
                ('frequency_target', models.IntegerField(default=10, help_text='Number of orders for maximum frequency score', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Frequency Target')),
                ('monetary_target', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Total spending for maximum monetary score', max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Monetary Target ($)')),
                ('first_purchase_discount', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='First Purchase Discount (%)')),
                ('birthday_discount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Birthday Discount (%)')),
                ('birthday_discount_days', models.IntegerField(default=7, help_text='Days before/after birthday when discount is active', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Birthday Discount Valid Days')),
                ('is_active', models.BooleanField(default=True, verbose_name='System Active')),
                ('max_total_discount', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Maximum combined discount (RFM + bonuses)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(75)], verbose_name='Max Total Discount (%)')),
            ],
            options={
                'verbose_name': 'Discount Settings',
                'verbose_name_plural': 'Discount Settings',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promo Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount depending on type', max_digits=10, verbose_name='Discount Value')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Minimum Order Amount')),
                ('max_uses', models.IntegerField(blank=True, help_text='Leave empty for unlimited', null=True, verbose_name='Max Total Uses')),
                ('max_uses_per_user', models.IntegerField(default=1, verbose_name='Max Uses Per User')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('times_used', models.IntegerField(default=0, verbose_name='Times Used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Total Orders')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Spent ($)')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Order Date')),
                ('recency_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, verbose_name='Recency Score (R)')),
                ('frequency_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, verbose_name='Frequency Score (F)')),
                ('monetary_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, verbose_name='Monetary Score (M)')),
                ('rfm_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4, verbose_name='RFM Score')),
                ('base_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Base Discount (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Discount Profile',
                'verbose_name_plural': 'Customer Discount Profiles',
            },
        ),
        migrations.CreateModel(
            name='DiscountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('rfm', 'RFM Personal Discount'), ('first_purchase', 'First Purchase Bonus'), ('birthday', 'Birthday Bonus'), ('promo', 'Promo Code')], max_length=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount Percent')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Amount ($)')),
                ('rfm_score_snapshot', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='RFM Score (at time of order)')),
                ('calculation_details', models.JSONField(blank=True, help_text='JSON with detailed calculation breakdown', null=True, verbose_name='Calculation Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_history', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount History',
                'verbose_name_plural': 'Discount Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Applied ($)')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_usage', to='orders.order')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
            },
        ),
    ]
