# Generated by Django 6.0.1 on 2026-02-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth Date Changed At'),
        ),
    ]
