# Generated by Django 6.0.1 on 2026-02-03 10:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount Percent'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo Code Used'),
        ),
    ]
