# Generated by Django 6.0.1 on 2026-02-04 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_beantype_price_multiplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_a', to='products.product')),
                ('product_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_b', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Similarity',
                'verbose_name_plural': 'Product Similarities',
                'indexes': [models.Index(fields=['product_a', 'similarity_score'], name='recommendat_product_68ea62_idx')],
                'unique_together': {('product_a', 'product_b')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('position', models.PositiveIntegerField()),
                ('was_clicked', models.BooleanField(default=False)),
                ('was_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Log',
                'verbose_name_plural': 'Recommendation Logs',
                'indexes': [models.Index(fields=['user', 'created_at'], name='recommendat_user_id_33d3be_idx'), models.Index(fields=['algorithm', 'was_clicked'], name='recommendat_algorit_f97618_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('cart', 'Add to Cart'), ('purchase', 'Purchase'), ('favorite', 'Favorite'), ('review', 'Review')], max_length=20)),
                ('interaction_count', models.PositiveIntegerField(default=1)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Product Interaction',
                'verbose_name_plural': 'User Product Interactions',
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='recommendat_user_id_0efd23_idx'), models.Index(fields=['product', 'interaction_type'], name='recommendat_product_89faf7_idx')],
                'unique_together': {('user', 'product', 'interaction_type')},
            },
        ),
    ]
