# Generated by Django 6.0.1 on 2026-02-05 12:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_content_based', models.DecimalField(decimal_places=2, default=Decimal('0.35'), help_text='Weight for content-based filtering (product similarity)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Content-Based Weight (α)')),
                ('weight_collaborative', models.DecimalField(decimal_places=2, default=Decimal('0.40'), help_text='Weight for collaborative filtering (user behavior)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Collaborative Weight (β)')),
                ('weight_popularity', models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Weight for popularity-based recommendations', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Popularity Weight (γ)')),
                ('feature_country_weight', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Country Feature Weight')),
                ('feature_roast_weight', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Roast Level Feature Weight')),
                ('feature_bean_weight', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Bean Type Feature Weight')),
                ('feature_price_weight', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Price Feature Weight')),
                ('time_decay_rate', models.DecimalField(decimal_places=3, default=Decimal('0.050'), help_text='Higher = interactions lose weight faster. Formula: weight × e^(-λt)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(1)], verbose_name='Time Decay Rate (λ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='System Active')),
                ('min_interactions_for_cf', models.IntegerField(default=3, help_text='Minimum user interactions to use collaborative filtering', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Min Interactions for CF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recommendation Settings',
                'verbose_name_plural': 'Recommendation Settings',
            },
        ),
    ]
