# Generated by Django 6.0.1 on 2026-02-02 08:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beantype',
            options={'verbose_name': 'Bean Type', 'verbose_name_plural': 'Bean Types'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='roastlevel',
            options={'verbose_name': 'Roast Level', 'verbose_name_plural': 'Roast Levels'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['grams'], 'verbose_name': 'Weight', 'verbose_name_plural': 'Weight Options'},
        ),
        migrations.RemoveField(
            model_name='weight',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='value',
        ),
        migrations.AddField(
            model_name='weight',
            name='grams',
            field=models.IntegerField(default=1, verbose_name='Weight (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weight',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Price Multiplier'),
        ),
        migrations.AlterField(
            model_name='beantype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_bean_types',
            field=models.ManyToManyField(related_name='products', to='products.beantype', verbose_name='Available Bean Types'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_weights',
            field=models.ManyToManyField(related_name='products', to='products.weight', verbose_name='Available Weights'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price (USD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='countries',
            field=models.ManyToManyField(related_name='products', to='products.country', verbose_name='Origin Countries'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='roast_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.roastlevel', verbose_name='Roast Level'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='taste_profile',
            field=models.TextField(blank=True, verbose_name='Taste Profile'),
        ),
        migrations.AlterField(
            model_name='roastlevel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
