# Generated by Django 6.0.1 on 2026-02-02 14:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_beantype_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beantype',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Price Multiplier'),
        ),
    ]
