# Generated by Django 6.0.1 on 2026-02-15 00:00

from decimal import Decimal
from django.db import migrations


def add_default_weight(apps, schema_editor):
    Weight = apps.get_model('products', 'Weight')
    Product = apps.get_model('products', 'Product')

    weight, _ = Weight.objects.get_or_create(
        grams=100,
        defaults={'price_multiplier': Decimal('1.00')}
    )

    for product in Product.objects.all():
        product.available_weights.add(weight)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_beantype_price_multiplier'),
    ]

    operations = [
        migrations.RunPython(add_default_weight, migrations.RunPython.noop),
    ]
